"use client";

import { ChangeEvent, FormEvent, useEffect, useState} from "react";
import Image from "next/image";
import Link from "next/link";
import { useRouter} from "next/navigation";
import { ArrowLeft, ImagePlus, X} from "lucide-react";
import { CountryCitySelect} from "@/components/location/CountryCitySelect";
import { createBrowserSupabaseClient} from "@/lib/supabase/client";
import { isHotelOperational} from "@/lib/hotel/access";
import { findCityById} from "@/lib/constants/world-city-helpers";
import { type WorldCity} from "@/lib/constants/world-cities";
import { structureTypeLabels, type StructureType} from "@/types/app";

type HotelForm = { id: string; property_name: string; structure_type: StructureType; cin_code: string; description: string; full_address: string; country_code: string; country_name: string; city_name: string; city_id: string; specific_area: string; rooms_quantity: number; main_photo_url: string; gallery_photo_urls: string[]; google_maps_url: string; public_email: string; public_phone: string};
const defaultCity = findCityById(null);
const MAX_GALLERY_PHOTOS = 4;
const emptyForm: HotelForm = { id: "", property_name: "", structure_type: "hotel", cin_code: "", description: "", full_address: "", country_code: defaultCity.country_code, country_name: defaultCity.country_name, city_name: defaultCity.city_name, city_id: defaultCity.city_id, specific_area: "", rooms_quantity: 1, main_photo_url: "", gallery_photo_urls: [], google_maps_url: "", public_email: "", public_phone: ""};
function fileExtension(file: File) { if (file.type === "image/png") return "png"; if (file.type === "image/webp") return "webp"; return "jpg";}

export function EditHotelProfileForm() {
  const router = useRouter();
  const [form, setForm] = useState<HotelForm>(emptyForm);
  const [selectedCity, setSelectedCity] = useState<WorldCity>(defaultCity);
  const [userId, setUserId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [hotelOperational, setHotelOperational] = useState(true);

  useEffect(() => { async function loadProfile() { setLoading(true); setError(null); try { const supabase = createBrowserSupabaseClient(); const { data: authData, error: authError} = await supabase.auth.getUser(); if (authError || !authData.user) { setError("Devi effettuare il login come struttura ricettiva."); return;} setUserId(authData.user.id); const { data, error: hotelError} = await supabase.from("hotel_accounts").select("id, property_name, structure_type, cin_code, description, full_address, country_code, country_name, city_name, city_id, specific_area, rooms_quantity, main_photo_url, gallery_photo_urls, google_maps_url, public_email, public_phone, subscription_active, account_status").eq("user_id", authData.user.id).single(); if (hotelError || !data) { setError("Profilo struttura non trovato."); return;} setHotelOperational(isHotelOperational(data)); const city = findCityById(data.city_id); setSelectedCity(city); setForm({ id: data.id, property_name: data.property_name ?? "", structure_type: data.structure_type ?? "hotel", cin_code: data.cin_code ?? "", description: data.description ?? "", full_address: data.full_address ?? "", country_code: city.country_code, country_name: city.country_name, city_name: city.city_name, city_id: city.city_id, specific_area: data.specific_area ?? "", rooms_quantity: data.rooms_quantity ?? 1, main_photo_url: data.main_photo_url ?? "", gallery_photo_urls: data.gallery_photo_urls ?? [], google_maps_url: data.google_maps_url ?? "", public_email: data.public_email ?? "", public_phone: data.public_phone ?? ""});} catch (err) { setError(err instanceof Error ? err.message : "Errore durante il caricamento del profilo.");} finally { setLoading(false);}} void loadProfile();}, []);
  function update<K extends keyof HotelForm>(key: K, value: HotelForm[K]) { setForm((current) => ({ ...current, [key]: value}));}
  function updateCity(city: WorldCity) { setSelectedCity(city); setForm((current) => ({ ...current, country_code: city.country_code, country_name: city.country_name, city_name: city.city_name, city_id: city.city_id}));}
  async function uploadPhoto(file: File, kind: "main" | "gallery") { if (!userId) throw new Error("Utente non trovato."); if (!file.type.startsWith("image/")) throw new Error("Carica solo immagini JPG, PNG o WEBP."); if (file.size > 5 * 1024 * 1024) throw new Error("La foto deve pesare massimo 5MB."); const supabase = createBrowserSupabaseClient(); const path = `${userId}/${kind}-${Date.now()}.${fileExtension(file)}`; const { error: uploadError} = await supabase.storage.from("hotel-photos").upload(path, file, { cacheControl: "3600", upsert: true}); if (uploadError) throw uploadError; const { data} = supabase.storage.from("hotel-photos").getPublicUrl(path); return data.publicUrl;}
  async function onMainPhotoChange(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(null); setSuccess(null); try { const url = await uploadPhoto(file, "main"); update("main_photo_url", url); setSuccess("Foto principale caricata. Ricorda di salvare il profilo.");} catch (err) { setError(err instanceof Error ? err.message : "Errore durante il caricamento della foto.");} finally { setUploading(false); event.target.value = "";}}
  async function onGalleryPhotoChange(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(null); setSuccess(null); try { if (form.gallery_photo_urls.length >= MAX_GALLERY_PHOTOS) { setError("Puoi caricare massimo 4 foto aggiuntive."); return;} const url = await uploadPhoto(file, "gallery"); update("gallery_photo_urls", [...form.gallery_photo_urls, url].slice(0, MAX_GALLERY_PHOTOS)); setSuccess("Foto galleria caricata. Ricorda di salvare il profilo.");} catch (err) { setError(err instanceof Error ? err.message : "Errore durante il caricamento della foto.");} finally { setUploading(false); event.target.value = "";}}
  function removeGalleryPhoto(index: number) { update("gallery_photo_urls", form.gallery_photo_urls.filter((_, photoIndex) => photoIndex !== index));}
  async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); setSuccess(null); try { const supabase = createBrowserSupabaseClient(); const { error: updateError} = await supabase.from("hotel_accounts").update({ property_name: form.property_name, structure_type: form.structure_type, cin_code: form.cin_code.trim() || null, description: form.description || null, full_address: form.full_address, country_code: form.country_code, country_name: form.country_name, city_name: form.city_name, city_id: form.city_id, specific_area: form.specific_area || null, rooms_quantity: form.rooms_quantity, main_photo_url: form.main_photo_url || null, gallery_photo_urls: form.gallery_photo_urls.slice(0, MAX_GALLERY_PHOTOS), google_maps_url: form.google_maps_url || null, public_email: form.public_email || null, public_phone: form.public_phone || null}).eq("id", form.id); if (updateError) { setError(updateError.message); return;} router.push(hotelOperational ? "/struttura/dashboard" : "/struttura/profilo"); return;} catch (err) { setError(err instanceof Error ? err.message : "Errore durante il salvataggio.");} finally { setSaving(false);}}
  if (loading) return <div className="rounded-3xl border p-6 text-sm text-zinc-500">Caricamento profilo struttura...</div>;

  return <div className="space-y-6"><Link href="/struttura/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-600 hover:text-zinc-950"><ArrowLeft className="h-4 w-4" /> Torna alla dashboard</Link>{error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : null}{success ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{success}</div> : null}<form onSubmit={onSubmit} className="space-y-6 rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm"><div><p className="text-sm font-medium uppercase tracking-wide text-emerald-700">Profilo struttura</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Modifica dati hotel</h1><p className="mt-2 text-sm text-zinc-500">Questi dati saranno visibili agli inserzionisti. Il CIN/codice registrazione è facoltativo e non viene mostrato negli annunci.</p></div><CountryCitySelect value={selectedCity} onChange={updateCity} countryLabel="Nazione struttura" cityLabel="Città principale struttura" helpText="La struttura riceverà annunci compatibili solo per questa città principale." />
  <div className="grid gap-5 md:grid-cols-2"><label className="block text-sm font-medium">Nome hotel / struttura<input value={form.property_name} onChange={(e) => update("property_name", e.target.value)} required className="mt-2 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm" /></label><label className="block text-sm font-medium">Tipologia<select value={form.structure_type} onChange={(e) => update("structure_type", e.target.value as StructureType)} className="mt-2 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm">{Object.entries(structureTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm font-medium">CIN / codice registrazione <span className="text-zinc-400">(facoltativo)</span><input value={form.cin_code} onChange={(e) => update("cin_code", e.target.value)} placeholder="Solo se previsto dalla normativa locale" className="mt-2 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm" /></label><label className="block text-sm font-medium">Camere / unità<input type="number" min={1} value={form.rooms_quantity} onChange={(e) => update("rooms_quantity", Number(e.target.value))} required className="mt-2 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm" /></label><label className="block text-sm font-medium md:col-span-2">Descrizione<textarea value={form.description} onChange={(e) => update("description", e.target.value)} rows={5} className="mt-2 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm" /></label>
  <section className="space-y-4 rounded-2xl border border-zinc-200 p-4 md:col-span-2"><div><h2 className="font-semibold">Foto hotel</h2><p className="mt-1 text-sm text-zinc-500">Carica massimo 5 foto: 1 principale + 4 aggiuntive. Formati accettati: JPG, PNG, WEBP. Max 5MB per foto.</p></div><div className="grid gap-4 md:grid-cols-[240px_1fr]"><div className="rounded-2xl border border-zinc-200 p-3"><p className="text-sm font-medium">Foto principale</p><div className="mt-3 aspect-video overflow-hidden rounded-2xl bg-zinc-100">{form.main_photo_url ? <Image src={form.main_photo_url} alt="Foto principale hotel" width={600} height={360} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-sm text-zinc-500">Nessuna foto</div>}</div><label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-full bg-zinc-950 px-4 py-2 text-sm font-semibold text-white"><ImagePlus className="h-4 w-4" /> {uploading ? "Caricamento..." : "Carica principale"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={onMainPhotoChange} disabled={uploading} className="sr-only" /></label></div><div className="rounded-2xl border border-zinc-200 p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">Foto aggiuntive ({form.gallery_photo_urls.length}/4)</p><label className={`inline-flex cursor-pointer items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold ${form.gallery_photo_urls.length >= MAX_GALLERY_PHOTOS ? "pointer-events-none opacity-50" : ""}`}><ImagePlus className="h-4 w-4" /> Aggiungi foto<input type="file" accept="image/jpeg,image/png,image/webp" onChange={onGalleryPhotoChange} disabled={uploading || form.gallery_photo_urls.length >= MAX_GALLERY_PHOTOS} className="sr-only" /></label></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{form.gallery_photo_urls.map((url, index) => <div key={url} className="relative aspect-video overflow-hidden rounded-2xl bg-zinc-100"><Image src={url} alt={`Foto hotel ${index + 1}`} width={300} height={180} className="h-full w-full object-cover" /><button type="button" onClick={() => removeGalleryPhoto(index)} className="absolute right-2 top-2 rounded-full bg-white/90 p-1 text-zinc-900 shadow-sm"><X className="h-4 w-4" /></button></div>)}{!form.gallery_photo_urls.length ? <p className="text-sm text-zinc-500">Nessuna foto aggiuntiva caricata.</p> : null}</div></div></div></section>
  <label className="block text-sm font-medium md:col-span-2">Indirizzo completo<input value={form.full_address} onChange={(e) => update("full_address", e.target.value)} required className="mt-2 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm" /></label><label className="block text-sm font-medium">Zona<input value={form.specific_area} onChange={(e) => update("specific_area", e.target.value)} placeholder="Centro, mare, aeroporto..." className="mt-2 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm" /></label>
  <div className="rounded-2xl border border-zinc-200 p-4 md:col-span-2"><label className="block text-sm font-medium">Google Maps URL<input value={form.google_maps_url} onChange={(e) => update("google_maps_url", e.target.value)} placeholder="https://maps.app.goo.gl/..." className="mt-2 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm" /></label><div className="mt-3 rounded-2xl bg-zinc-50 p-4 text-sm text-zinc-600"><p className="font-semibold text-zinc-800">Come trovare il link corretto:</p><ol className="mt-2 list-decimal space-y-1 pl-5"><li>Apri l’app Google Maps.</li><li>Cerca l’hotel.</li><li>Apri la scheda dell’hotel.</li><li>Tocca Condividi.</li><li>Tocca Copia link.</li><li>Incollalo in questo campo.</li></ol></div></div><label className="block text-sm font-medium">Email pubblica<input value={form.public_email} onChange={(e) => update("public_email", e.target.value)} className="mt-2 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm" /></label><label className="block text-sm font-medium">Telefono pubblico<input value={form.public_phone} onChange={(e) => update("public_phone", e.target.value)} className="mt-2 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-sm" /></label></div><button disabled={saving || uploading} type="submit" className="rounded-full bg-zinc-950 px-6 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving ? "Salvataggio..." : uploading ? "Caricamento foto..." : "Salva profilo struttura"}</button></form></div>;
}
