-- 4 hotel onboarding a Regina, Saskatchewan (Canada)
-- Esegui in Supabase SQL Editor (idempotente su place_id)

insert into public.onboarding_hotels (
  place_id,
  nome,
  indirizzo,
  city_name,
  lat,
  lng,
  phone,
  email,
  website,
  google_maps_url,
  description,
  description_en,
  status,
  slug,
  seo_indexable
) values
  (
    'manual:ca-reg:hotel-saskatchewan-autograph',
    'The Hotel Saskatchewan, Autograph Collection',
    '2125 Victoria Avenue, Regina, SK S4P 0S3, Canada',
    'Regina',
    50.4422,
    -104.6107,
    '+1 306-522-7691',
    'info@hotelsask.com',
    'https://www.marriott.com/en-us/hotels/yqrak-the-hotel-saskatchewan-autograph-collection/overview/',
    'https://www.google.com/maps/search/?api=1&query=The+Hotel+Saskatchewan+Regina',
    'Hotel storico di lusso su Victoria Avenue, nel centro di Regina, Saskatchewan. Camere eleganti, ristorazione e spazi eventi nel cuore delle praterie canadesi.',
    'The Hotel Saskatchewan, Autograph Collection is a historic luxury hotel on Victoria Avenue in downtown Regina, Saskatchewan. Elegant rooms, dining and event spaces in the heart of the Canadian Prairies.',
    'unclaimed',
    'the-hotel-saskatchewan-autograph-collection-regina',
    true
  ),
  (
    'manual:ca-reg:delta-hotels-marriott-regina',
    'Delta Hotels by Marriott Regina',
    '1919 Saskatchewan Drive, Regina, SK S4P 4H2, Canada',
    'Regina',
    50.4076,
    -104.5869,
    '+1 306-525-5255',
    null,
    'https://www.marriott.com/en-us/hotels/yqrak-delta-hotels-regina/overview/',
    'https://www.google.com/maps/search/?api=1&query=Delta+Hotels+Marriott+Regina',
    'Delta Hotels by Marriott Regina: hotel moderno vicino al Wascana Centre, ideale per viaggi di lavoro e soggiorni leisure a Regina, Saskatchewan.',
    'Delta Hotels by Marriott Regina offers modern rooms and amenities near Wascana Centre — a convenient base for business and leisure stays in Regina, Saskatchewan.',
    'unclaimed',
    'delta-hotels-by-marriott-regina-regina',
    true
  ),
  (
    'manual:ca-reg:best-western-plus-eastgate',
    'Best Western Plus Eastgate Inn & Suites',
    '3840 Eastgate Drive, Regina, SK S4Z 1A5, Canada',
    'Regina',
    50.4739,
    -104.5694,
    '+1 306-352-7587',
    null,
    'https://www.bestwestern.com/en_US/book/hotels-in-regina/best-western-plus-eastgate-inn-suites/propertyCode.68028.html',
    'https://www.google.com/maps/search/?api=1&query=Best+Western+Plus+Eastgate+Regina',
    'Best Western Plus Eastgate Inn & Suites: hotel confortevole nella zona est di Regina, con suite, colazione e accesso rapido alle principali arterie della città.',
    'Best Western Plus Eastgate Inn & Suites is a comfortable hotel on Regina''s east side, with suites, breakfast and quick access to major city routes.',
    'unclaimed',
    'best-western-plus-eastgate-inn-suites-regina',
    true
  ),
  (
    'manual:ca-reg:courtyard-marriott-downtown',
    'Courtyard by Marriott Regina Downtown',
    '1717 Victoria Avenue, Regina, SK S4P 0P9, Canada',
    'Regina',
    50.4438,
    -104.6195,
    '+1 306-559-5682',
    null,
    'https://www.marriott.com/en-us/hotels/yqrcy-courtyard-regina-downtown/overview/',
    'https://www.google.com/maps/search/?api=1&query=Courtyard+Marriott+Regina+Downtown',
    'Courtyard by Marriott Regina Downtown: hotel contemporaneo nel centro di Regina, a due passi da Victoria Avenue, ristorazione e uffici del downtown.',
    'Courtyard by Marriott Regina Downtown is a contemporary hotel in central Regina, steps from Victoria Avenue, dining and downtown offices.',
    'unclaimed',
    'courtyard-by-marriott-regina-downtown-regina',
    true
  )
on conflict (place_id) do update set
  nome = excluded.nome,
  indirizzo = excluded.indirizzo,
  city_name = excluded.city_name,
  lat = excluded.lat,
  lng = excluded.lng,
  phone = excluded.phone,
  email = excluded.email,
  website = excluded.website,
  google_maps_url = excluded.google_maps_url,
  description = excluded.description,
  description_en = excluded.description_en,
  slug = excluded.slug,
  seo_indexable = excluded.seo_indexable,
  updated_at = now();
