export type WorldCity = {
  label: string;
  country_code: string;
  country_name: string;
  city_name: string;
  city_id: string;
};

export const majorWorldCities: WorldCity[] = [
  { label: "New York, United States", country_code: "US", country_name: "United States", city_name: "New York", city_id: "US-NYC"},
  { label: "Los Angeles, United States", country_code: "US", country_name: "United States", city_name: "Los Angeles", city_id: "US-LAX"},
  { label: "Miami, United States", country_code: "US", country_name: "United States", city_name: "Miami", city_id: "US-MIA"},
  { label: "London, United Kingdom", country_code: "GB", country_name: "United Kingdom", city_name: "London", city_id: "GB-LON"},
  { label: "Paris, France", country_code: "FR", country_name: "France", city_name: "Paris", city_id: "FR-PAR"},

  { label: "Agrigento, Italy", country_code: "IT", country_name: "Italy", city_name: "Agrigento", city_id: "IT-AGR"},
  { label: "Alba, Italy", country_code: "IT", country_name: "Italy", city_name: "Alba", city_id: "IT-ALB"},
  { label: "Alberobello, Italy", country_code: "IT", country_name: "Italy", city_name: "Alberobello", city_id: "IT-ABB"},
  { label: "Alghero, Italy", country_code: "IT", country_name: "Italy", city_name: "Alghero", city_id: "IT-AHO"},
  { label: "Ancona, Italy", country_code: "IT", country_name: "Italy", city_name: "Ancona", city_id: "IT-AOI"},
  { label: "Aosta, Italy", country_code: "IT", country_name: "Italy", city_name: "Aosta", city_id: "IT-AOT"},
  { label: "Arezzo, Italy", country_code: "IT", country_name: "Italy", city_name: "Arezzo", city_id: "IT-ARZ"},
  { label: "Assisi, Italy", country_code: "IT", country_name: "Italy", city_name: "Assisi", city_id: "IT-ASS"},
  { label: "Bari, Italy", country_code: "IT", country_name: "Italy", city_name: "Bari", city_id: "IT-BRI"},
  { label: "Bergamo, Italy", country_code: "IT", country_name: "Italy", city_name: "Bergamo", city_id: "IT-BGY"},
  { label: "Bologna, Italy", country_code: "IT", country_name: "Italy", city_name: "Bologna", city_id: "IT-BLQ"},
  { label: "Bolzano, Italy", country_code: "IT", country_name: "Italy", city_name: "Bolzano", city_id: "IT-BZO"},
  { label: "Brescia, Italy", country_code: "IT", country_name: "Italy", city_name: "Brescia", city_id: "IT-BSC"},
  { label: "Brindisi, Italy", country_code: "IT", country_name: "Italy", city_name: "Brindisi", city_id: "IT-BDS"},
  { label: "Cagliari, Italy", country_code: "IT", country_name: "Italy", city_name: "Cagliari", city_id: "IT-CAG"},
  { label: "Capri, Italy", country_code: "IT", country_name: "Italy", city_name: "Capri", city_id: "IT-CAP"},
  { label: "Catania, Italy", country_code: "IT", country_name: "Italy", city_name: "Catania", city_id: "IT-CTA"},
  { label: "Cefalù, Italy", country_code: "IT", country_name: "Italy", city_name: "Cefalù", city_id: "IT-CEF"},
  { label: "Cinque Terre, Italy", country_code: "IT", country_name: "Italy", city_name: "Cinque Terre", city_id: "IT-CQT"},
  { label: "Como, Italy", country_code: "IT", country_name: "Italy", city_name: "Como", city_id: "IT-CMO"},
  { label: "Cortina d’Ampezzo, Italy", country_code: "IT", country_name: "Italy", city_name: "Cortina d’Ampezzo", city_id: "IT-COR"},
  { label: "Desenzano del Garda, Italy", country_code: "IT", country_name: "Italy", city_name: "Desenzano del Garda", city_id: "IT-DES"},
  { label: "Ferrara, Italy", country_code: "IT", country_name: "Italy", city_name: "Ferrara", city_id: "IT-FER"},
  { label: "Florence, Italy", country_code: "IT", country_name: "Italy", city_name: "Florence", city_id: "IT-FLR"},
  { label: "Garda, Italy", country_code: "IT", country_name: "Italy", city_name: "Garda", city_id: "IT-GAR"},
  { label: "Genoa, Italy", country_code: "IT", country_name: "Italy", city_name: "Genoa", city_id: "IT-GOA"},
  { label: "Jesolo, Italy", country_code: "IT", country_name: "Italy", city_name: "Jesolo", city_id: "IT-JES"},
  { label: "Lecce, Italy", country_code: "IT", country_name: "Italy", city_name: "Lecce", city_id: "IT-LCC"},
  { label: "Livorno, Italy", country_code: "IT", country_name: "Italy", city_name: "Livorno", city_id: "IT-LIV"},
  { label: "Lucca, Italy", country_code: "IT", country_name: "Italy", city_name: "Lucca", city_id: "IT-LUC"},
  { label: "Mantua, Italy", country_code: "IT", country_name: "Italy", city_name: "Mantua", city_id: "IT-MNT"},
  { label: "Matera, Italy", country_code: "IT", country_name: "Italy", city_name: "Matera", city_id: "IT-MAT"},
  { label: "Merano, Italy", country_code: "IT", country_name: "Italy", city_name: "Merano", city_id: "IT-MER"},
  { label: "Milan, Italy", country_code: "IT", country_name: "Italy", city_name: "Milan", city_id: "IT-MIL"},
  { label: "Modena, Italy", country_code: "IT", country_name: "Italy", city_name: "Modena", city_id: "IT-MOD"},
  { label: "Monopoli, Italy", country_code: "IT", country_name: "Italy", city_name: "Monopoli", city_id: "IT-MON"},
  { label: "Naples, Italy", country_code: "IT", country_name: "Italy", city_name: "Naples", city_id: "IT-NAP"},
  { label: "Olbia, Italy", country_code: "IT", country_name: "Italy", city_name: "Olbia", city_id: "IT-OLB"},
  { label: "Padua, Italy", country_code: "IT", country_name: "Italy", city_name: "Padua", city_id: "IT-PAD"},
  { label: "Palermo, Italy", country_code: "IT", country_name: "Italy", city_name: "Palermo", city_id: "IT-PMO"},
  { label: "Parma, Italy", country_code: "IT", country_name: "Italy", city_name: "Parma", city_id: "IT-PMF"},
  { label: "Perugia, Italy", country_code: "IT", country_name: "Italy", city_name: "Perugia", city_id: "IT-PEG"},
  { label: "Pescara, Italy", country_code: "IT", country_name: "Italy", city_name: "Pescara", city_id: "IT-PSR"},
  { label: "Pisa, Italy", country_code: "IT", country_name: "Italy", city_name: "Pisa", city_id: "IT-PSA"},
  { label: "Polignano a Mare, Italy", country_code: "IT", country_name: "Italy", city_name: "Polignano a Mare", city_id: "IT-POL"},
  { label: "Portofino, Italy", country_code: "IT", country_name: "Italy", city_name: "Portofino", city_id: "IT-POF"},
  { label: "Ravenna, Italy", country_code: "IT", country_name: "Italy", city_name: "Ravenna", city_id: "IT-RAV"},
  { label: "Reggio Calabria, Italy", country_code: "IT", country_name: "Italy", city_name: "Reggio Calabria", city_id: "IT-REG"},
  { label: "Rimini, Italy", country_code: "IT", country_name: "Italy", city_name: "Rimini", city_id: "IT-RMI"},
  { label: "Rome, Italy", country_code: "IT", country_name: "Italy", city_name: "Rome", city_id: "IT-ROM"},
  { label: "Salerno, Italy", country_code: "IT", country_name: "Italy", city_name: "Salerno", city_id: "IT-SAL"},
  { label: "San Gimignano, Italy", country_code: "IT", country_name: "Italy", city_name: "San Gimignano", city_id: "IT-SGI"},
  { label: "Sanremo, Italy", country_code: "IT", country_name: "Italy", city_name: "Sanremo", city_id: "IT-SRM"},
  { label: "Siena, Italy", country_code: "IT", country_name: "Italy", city_name: "Siena", city_id: "IT-SIE"},
  { label: "Sirmione, Italy", country_code: "IT", country_name: "Italy", city_name: "Sirmione", city_id: "IT-SIR"},
  { label: "Sorrento, Italy", country_code: "IT", country_name: "Italy", city_name: "Sorrento", city_id: "IT-SOR"},
  { label: "Taormina, Italy", country_code: "IT", country_name: "Italy", city_name: "Taormina", city_id: "IT-TAO"},
  { label: "Taranto, Italy", country_code: "IT", country_name: "Italy", city_name: "Taranto", city_id: "IT-TAR"},
  { label: "Trieste, Italy", country_code: "IT", country_name: "Italy", city_name: "Trieste", city_id: "IT-TRS"},
  { label: "Turin, Italy", country_code: "IT", country_name: "Italy", city_name: "Turin", city_id: "IT-TRN"},
  { label: "Venice, Italy", country_code: "IT", country_name: "Italy", city_name: "Venice", city_id: "IT-VCE"},
  { label: "Verona, Italy", country_code: "IT", country_name: "Italy", city_name: "Verona", city_id: "IT-VRN"},
  { label: "Viareggio, Italy", country_code: "IT", country_name: "Italy", city_name: "Viareggio", city_id: "IT-VIA"},
  { label: "Vicenza, Italy", country_code: "IT", country_name: "Italy", city_name: "Vicenza", city_id: "IT-VIC"},

  { label: "Madrid, Spain", country_code: "ES", country_name: "Spain", city_name: "Madrid", city_id: "ES-MAD"},
  { label: "Barcelona, Spain", country_code: "ES", country_name: "Spain", city_name: "Barcelona", city_id: "ES-BCN"},
  { label: "Berlin, Germany", country_code: "DE", country_name: "Germany", city_name: "Berlin", city_id: "DE-BER"},
  { label: "Amsterdam, Netherlands", country_code: "NL", country_name: "Netherlands", city_name: "Amsterdam", city_id: "NL-AMS"},
  { label: "Lisbon, Portugal", country_code: "PT", country_name: "Portugal", city_name: "Lisbon", city_id: "PT-LIS"},
  { label: "Dubai, United Arab Emirates", country_code: "AE", country_name: "United Arab Emirates", city_name: "Dubai", city_id: "AE-DXB"},
  { label: "Doha, Qatar", country_code: "QA", country_name: "Qatar", city_name: "Doha", city_id: "QA-DOH"},
  { label: "Istanbul, Turkey", country_code: "TR", country_name: "Turkey", city_name: "Istanbul", city_id: "TR-IST"},
  { label: "Bangkok, Thailand", country_code: "TH", country_name: "Thailand", city_name: "Bangkok", city_id: "TH-BKK"},
  { label: "Phuket, Thailand", country_code: "TH", country_name: "Thailand", city_name: "Phuket", city_id: "TH-HKT"},
  { label: "Singapore, Singapore", country_code: "SG", country_name: "Singapore", city_name: "Singapore", city_id: "SG-SIN"},
  { label: "Tokyo, Japan", country_code: "JP", country_name: "Japan", city_name: "Tokyo", city_id: "JP-TYO"},
  { label: "Seoul, South Korea", country_code: "KR", country_name: "South Korea", city_name: "Seoul", city_id: "KR-SEL"},
  { label: "Hong Kong, Hong Kong", country_code: "HK", country_name: "Hong Kong", city_name: "Hong Kong", city_id: "HK-HKG"},
  { label: "Shanghai, China", country_code: "CN", country_name: "China", city_name: "Shanghai", city_id: "CN-SHA"},
  { label: "Beijing, China", country_code: "CN", country_name: "China", city_name: "Beijing", city_id: "CN-BJS"},
  { label: "Sydney, Australia", country_code: "AU", country_name: "Australia", city_name: "Sydney", city_id: "AU-SYD"},
  { label: "Melbourne, Australia", country_code: "AU", country_name: "Australia", city_name: "Melbourne", city_id: "AU-MEL"},
  { label: "Toronto, Canada", country_code: "CA", country_name: "Canada", city_name: "Toronto", city_id: "CA-TOR"},
  { label: "Vancouver, Canada", country_code: "CA", country_name: "Canada", city_name: "Vancouver", city_id: "CA-YVR"},
  { label: "Mexico City, Mexico", country_code: "MX", country_name: "Mexico", city_name: "Mexico City", city_id: "MX-MEX"},
  { label: "Rio de Janeiro, Brazil", country_code: "BR", country_name: "Brazil", city_name: "Rio de Janeiro", city_id: "BR-RIO"},
  { label: "São Paulo, Brazil", country_code: "BR", country_name: "Brazil", city_name: "São Paulo", city_id: "BR-SAO"},
  { label: "Buenos Aires, Argentina", country_code: "AR", country_name: "Argentina", city_name: "Buenos Aires", city_id: "AR-BUE"},
  { label: "Cape Town, South Africa", country_code: "ZA", country_name: "South Africa", city_name: "Cape Town", city_id: "ZA-CPT"},
  { label: "Marrakesh, Morocco", country_code: "MA", country_name: "Morocco", city_name: "Marrakesh", city_id: "MA-RAK"},
  { label: "Cairo, Egypt", country_code: "EG", country_name: "Egypt", city_name: "Cairo", city_id: "EG-CAI"}
];
