import comuniData from "@/public/data/comuni.json";

export type GeoContext = {
  provinceCode: string;
  provinceName: string;
  regionName: string;
  macroAreaIt: "Nord Italia" | "Centro Italia" | "Sud Italia";
  macroAreaEn: "Northern Italy" | "Central Italy" | "Southern Italy";
};

const PROVINCE_NAMES: Record<string, string> = {
  AG: "Agrigento",
  AL: "Alessandria",
  AN: "Ancona",
  AO: "Aosta",
  AP: "Ascoli Piceno",
  AQ: "L'Aquila",
  AR: "Arezzo",
  AT: "Asti",
  AV: "Avellino",
  BA: "Bari",
  BG: "Bergamo",
  BI: "Biella",
  BL: "Belluno",
  BN: "Benevento",
  BO: "Bologna",
  BR: "Brindisi",
  BS: "Brescia",
  BT: "Barletta-Andria-Trani",
  CA: "Cagliari",
  CB: "Campobasso",
  CE: "Caserta",
  CH: "Chieti",
  CL: "Caltanissetta",
  CN: "Cuneo",
  CO: "Como",
  CR: "Cremona",
  CS: "Cosenza",
  CT: "Catania",
  CZ: "Catanzaro",
  EN: "Enna",
  FC: "Forlì-Cesena",
  FE: "Ferrara",
  FG: "Foggia",
  FI: "Firenze",
  FM: "Fermo",
  FR: "Frosinone",
  GE: "Genova",
  GO: "Gorizia",
  GR: "Grosseto",
  IM: "Imperia",
  IS: "Isernia",
  KR: "Crotone",
  LC: "Lecco",
  LE: "Lecce",
  LI: "Livorno",
  LO: "Lodi",
  LT: "Latina",
  LU: "Lucca",
  MB: "Monza e Brianza",
  MC: "Macerata",
  ME: "Messina",
  MI: "Milano",
  MN: "Mantova",
  MO: "Modena",
  MS: "Massa-Carrara",
  MT: "Matera",
  NA: "Napoli",
  NO: "Novara",
  NU: "Nuoro",
  OR: "Oristano",
  PA: "Palermo",
  PC: "Piacenza",
  PD: "Padova",
  PE: "Pescara",
  PG: "Perugia",
  PI: "Pisa",
  PN: "Pordenone",
  PO: "Prato",
  PR: "Parma",
  PT: "Pistoia",
  PU: "Pesaro e Urbino",
  PV: "Pavia",
  PZ: "Potenza",
  RA: "Ravenna",
  RC: "Reggio Calabria",
  RE: "Reggio Emilia",
  RG: "Ragusa",
  RI: "Rieti",
  RM: "Roma",
  RN: "Rimini",
  RO: "Rovigo",
  SA: "Salerno",
  SI: "Siena",
  SO: "Sondrio",
  SP: "La Spezia",
  SR: "Siracusa",
  SS: "Sassari",
  SU: "Sud Sardegna",
  SV: "Savona",
  TA: "Taranto",
  TE: "Teramo",
  TN: "Trento",
  TO: "Torino",
  TP: "Trapani",
  TR: "Terni",
  TS: "Trieste",
  TV: "Treviso",
  UD: "Udine",
  VA: "Varese",
  VB: "Verbano-Cusio-Ossola",
  VC: "Vercelli",
  VE: "Venezia",
  VI: "Vicenza",
  VR: "Verona",
  VT: "Viterbo",
  VV: "Vibo Valentia",
};

const PROVINCE_TO_REGION: Record<string, string> = {
  AG: "Sicilia",
  AL: "Piemonte",
  AN: "Marche",
  AO: "Valle d'Aosta",
  AP: "Marche",
  AQ: "Abruzzo",
  AR: "Toscana",
  AT: "Piemonte",
  AV: "Campania",
  BA: "Puglia",
  BG: "Lombardia",
  BI: "Piemonte",
  BL: "Veneto",
  BN: "Campania",
  BO: "Emilia-Romagna",
  BR: "Puglia",
  BS: "Lombardia",
  BT: "Puglia",
  CA: "Sardegna",
  CB: "Molise",
  CE: "Campania",
  CH: "Abruzzo",
  CL: "Sicilia",
  CN: "Piemonte",
  CO: "Lombardia",
  CR: "Lombardia",
  CS: "Calabria",
  CT: "Sicilia",
  CZ: "Calabria",
  EN: "Sicilia",
  FC: "Emilia-Romagna",
  FE: "Emilia-Romagna",
  FG: "Puglia",
  FI: "Toscana",
  FM: "Marche",
  FR: "Lazio",
  GE: "Liguria",
  GO: "Friuli-Venezia Giulia",
  GR: "Toscana",
  IM: "Liguria",
  IS: "Molise",
  KR: "Calabria",
  LC: "Lombardia",
  LE: "Puglia",
  LI: "Toscana",
  LO: "Lombardia",
  LT: "Lazio",
  LU: "Toscana",
  MB: "Lombardia",
  MC: "Marche",
  ME: "Sicilia",
  MI: "Lombardia",
  MN: "Lombardia",
  MO: "Emilia-Romagna",
  MS: "Toscana",
  MT: "Basilicata",
  NA: "Campania",
  NO: "Piemonte",
  NU: "Sardegna",
  OR: "Sardegna",
  PA: "Sicilia",
  PC: "Emilia-Romagna",
  PD: "Veneto",
  PE: "Abruzzo",
  PG: "Umbria",
  PI: "Toscana",
  PN: "Friuli-Venezia Giulia",
  PO: "Toscana",
  PR: "Emilia-Romagna",
  PT: "Toscana",
  PU: "Marche",
  PV: "Lombardia",
  PZ: "Basilicata",
  RA: "Emilia-Romagna",
  RC: "Calabria",
  RE: "Emilia-Romagna",
  RG: "Sicilia",
  RI: "Lazio",
  RM: "Lazio",
  RN: "Emilia-Romagna",
  RO: "Veneto",
  SA: "Campania",
  SI: "Toscana",
  SO: "Lombardia",
  SP: "Liguria",
  SR: "Sicilia",
  SS: "Sardegna",
  SU: "Sardegna",
  SV: "Liguria",
  TA: "Puglia",
  TE: "Abruzzo",
  TN: "Trentino-Alto Adige",
  TO: "Piemonte",
  TP: "Sicilia",
  TR: "Umbria",
  TS: "Friuli-Venezia Giulia",
  TV: "Veneto",
  UD: "Friuli-Venezia Giulia",
  VA: "Lombardia",
  VB: "Piemonte",
  VC: "Piemonte",
  VE: "Veneto",
  VI: "Veneto",
  VR: "Veneto",
  VT: "Lazio",
  VV: "Calabria",
};

const REGION_MACRO: Record<string, { it: GeoContext["macroAreaIt"]; en: GeoContext["macroAreaEn"] }> = {
  Abruzzo: { it: "Sud Italia", en: "Southern Italy" },
  Basilicata: { it: "Sud Italia", en: "Southern Italy" },
  Calabria: { it: "Sud Italia", en: "Southern Italy" },
  Campania: { it: "Sud Italia", en: "Southern Italy" },
  "Emilia-Romagna": { it: "Nord Italia", en: "Northern Italy" },
  "Friuli-Venezia Giulia": { it: "Nord Italia", en: "Northern Italy" },
  Lazio: { it: "Centro Italia", en: "Central Italy" },
  Liguria: { it: "Nord Italia", en: "Northern Italy" },
  Lombardia: { it: "Nord Italia", en: "Northern Italy" },
  Marche: { it: "Centro Italia", en: "Central Italy" },
  Molise: { it: "Sud Italia", en: "Southern Italy" },
  Piemonte: { it: "Nord Italia", en: "Northern Italy" },
  Puglia: { it: "Sud Italia", en: "Southern Italy" },
  Sardegna: { it: "Sud Italia", en: "Southern Italy" },
  Sicilia: { it: "Sud Italia", en: "Southern Italy" },
  Toscana: { it: "Centro Italia", en: "Central Italy" },
  "Trentino-Alto Adige": { it: "Nord Italia", en: "Northern Italy" },
  Umbria: { it: "Centro Italia", en: "Central Italy" },
  "Valle d'Aosta": { it: "Nord Italia", en: "Northern Italy" },
  Veneto: { it: "Nord Italia", en: "Northern Italy" },
};

const cityToProvince = new Map<string, string>();

for (const row of comuniData as Array<{ name: string; province: string }>) {
  cityToProvince.set(row.name.trim().toLocaleLowerCase("it-IT"), row.province.trim().toUpperCase());
}

export function resolveGeoContext(cityName: string, countryName: string): GeoContext | null {
  const country = countryName.trim().toLowerCase();
  if (country !== "italia" && country !== "italy" && country !== "it") return null;

  const provinceCode = cityToProvince.get(cityName.trim().toLocaleLowerCase("it-IT"));
  if (!provinceCode) return null;

  const regionName = PROVINCE_TO_REGION[provinceCode];
  const provinceName = PROVINCE_NAMES[provinceCode] ?? provinceCode;
  const macro = regionName ? REGION_MACRO[regionName] : null;
  if (!regionName || !macro) return null;

  return {
    provinceCode,
    provinceName,
    regionName,
    macroAreaIt: macro.it,
    macroAreaEn: macro.en,
  };
}

/** "a Roma" vs "ad Agrigento" */
export function italianInCity(cityName: string): string {
  const trimmed = cityName.trim();
  if (/^[aeiouàèéìíîòóùú]/i.test(trimmed)) return `ad ${trimmed}`;
  return `a ${trimmed}`;
}

export function buildStructureGeoSubtitle(cityName: string, countryName: string, locale: "it" | "en"): string | null {
  const geo = resolveGeoContext(cityName, countryName);
  if (!geo) return null;
  if (locale === "en") {
    return `${geo.regionName} · ${geo.macroAreaEn}`;
  }
  return `${geo.regionName} · ${geo.macroAreaIt}`;
}
